function [verts, normals] = read_pcloud_obj(filename)

% read_point_obj - load a .obj point cloud file.
%
%   [verts,normals] = read_point_obj(inputmesh);
%
% verts  : node coordinatates
%
%(C) JJCAO
% Update history 2009.10.13

i=0;
fid=fopen(filename);
while ~feof(fid)
    tline = fgetl(fid);
    i=i+1;
    if strcmp(tline,'# Studio')
        [verts, normals] = read_studio_obj(fid);
        break;
    elseif strcmp(tline,'# OBJ File Generated by Meshlab') 
        [verts, normals] = read_meshlab_obj(fid);
        break;
    elseif i>3
        [verts, normals] = read_adrea_obj(fid);
        break;
    end    
end

fclose(fid);

%--------------------------------------------------------------------------
function [verts, normals] = read_meshlab_obj(fid)
for i = 1:5
    tline = fgetl(fid);
end
tmp = sscanf(tline,'%*s %*s %f');
nverts = tmp(1);
for i = 1:3
    tline = fgetl(fid);
end

verts = zeros(nverts,3);
normals = zeros(nverts,3);
i=1;
while ~feof(fid)
    tline = fgetl(fid);
    tmp = sscanf(tline,'%s %f %f %f', 5);
    normals(i,:) = tmp(3:5);
    tline = fgetl(fid);
    tmp = sscanf(tline,'%s %f %f %f', 4);
    verts(i,:) = tmp(2:4);   
    
    i = i+1;
    if i == nverts
        break;
    end
end

%--------------------------------------------------------------------------
function [verts, normals] = read_studio_obj(fid)
fseek(fid, -20, 'eof');
nverts = fscanf(fid,'%f');
verts = zeros(nverts,3);
normals = [];

frewind(fid);
tline = fgetl(fid);
tline = fgetl(fid);
for i = 1:nverts
    fseek(fid, 2, 'cof');
    verts(i,:) = fscanf(fid,'%f %f %f');
    fgetl(fid);    
end

%--------------------------------------------------------------------------
function [verts, normals] = read_adrea_obj(fid)
frewind(fid);
i = 0;
while ~feof(fid)
    tmp = fgetl(fid);
    i = i+1;
end
frewind(fid);
if strcmp('vn',tmp(1:2))
    nverts = i/2;
else
    nverts = i;
end

[A,cnt] = fscanf(fid,'%s %f %f %f', 4*nverts);
A = reshape(A, 4, length(A)/4);
A = A(2:end,:);
verts = A';
 
if nverts == i/2
    [A,cnt] = fscanf(fid,'%s %f %f %f', 5*nverts);
    A = reshape(A, 5, length(A)/5);
    A = A(3:end,:);
    normals = A';
else
    normals = [];
end